// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: streamline/v1/feature_registry.proto

package featurepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FeatureType represents the set of supported feature types.
// Each has a different Redis storage strategy.
type FeatureType int32

const (
	FeatureType_FEATURE_TYPE_UNSPECIFIED  FeatureType = 0
	FeatureType_FEATURE_TYPE_COUNT        FeatureType = 1 // counter incremented per event
	FeatureType_FEATURE_TYPE_NUMERIC      FeatureType = 2 // measured value, aggregated across events
	FeatureType_FEATURE_TYPE_RATIO        FeatureType = 3 // matching events / total events
	FeatureType_FEATURE_TYPE_HLL_DISTINCT FeatureType = 4 // approximate cardinality of a field
	FeatureType_FEATURE_TYPE_ENTROPY      FeatureType = 5 // Shannon entropy over a field's distribution
	FeatureType_FEATURE_TYPE_TIME_GAP     FeatureType = 6 // seconds since the visitor's last event
)

// Enum value maps for FeatureType.
var (
	FeatureType_name = map[int32]string{
		0: "FEATURE_TYPE_UNSPECIFIED",
		1: "FEATURE_TYPE_COUNT",
		2: "FEATURE_TYPE_NUMERIC",
		3: "FEATURE_TYPE_RATIO",
		4: "FEATURE_TYPE_HLL_DISTINCT",
		5: "FEATURE_TYPE_ENTROPY",
		6: "FEATURE_TYPE_TIME_GAP",
	}
	FeatureType_value = map[string]int32{
		"FEATURE_TYPE_UNSPECIFIED":  0,
		"FEATURE_TYPE_COUNT":        1,
		"FEATURE_TYPE_NUMERIC":      2,
		"FEATURE_TYPE_RATIO":        3,
		"FEATURE_TYPE_HLL_DISTINCT": 4,
		"FEATURE_TYPE_ENTROPY":      5,
		"FEATURE_TYPE_TIME_GAP":     6,
	}
)

func (x FeatureType) Enum() *FeatureType {
	p := new(FeatureType)
	*p = x
	return p
}

func (x FeatureType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FeatureType) Descriptor() protoreflect.EnumDescriptor {
	return file_streamline_v1_feature_registry_proto_enumTypes[0].Descriptor()
}

func (FeatureType) Type() protoreflect.EnumType {
	return &file_streamline_v1_feature_registry_proto_enumTypes[0]
}

func (x FeatureType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FeatureType.Descriptor instead.
func (FeatureType) EnumDescriptor() ([]byte, []int) {
	return file_streamline_v1_feature_registry_proto_rawDescGZIP(), []int{0}
}

// Transform applied to feature values before histogram fitting and scoring.
type Transform int32

const (
	Transform_TRANSFORM_UNSPECIFIED Transform = 0
	Transform_TRANSFORM_IDENTITY    Transform = 1 // use the raw feature value
	Transform_TRANSFORM_LOG1P       Transform = 2 // log(1+x); compresses wide-range count features
)

// Enum value maps for Transform.
var (
	Transform_name = map[int32]string{
		0: "TRANSFORM_UNSPECIFIED",
		1: "TRANSFORM_IDENTITY",
		2: "TRANSFORM_LOG1P",
	}
	Transform_value = map[string]int32{
		"TRANSFORM_UNSPECIFIED": 0,
		"TRANSFORM_IDENTITY":    1,
		"TRANSFORM_LOG1P":       2,
	}
)

func (x Transform) Enum() *Transform {
	p := new(Transform)
	*p = x
	return p
}

func (x Transform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Transform) Descriptor() protoreflect.EnumDescriptor {
	return file_streamline_v1_feature_registry_proto_enumTypes[1].Descriptor()
}

func (Transform) Type() protoreflect.EnumType {
	return &file_streamline_v1_feature_registry_proto_enumTypes[1]
}

func (x Transform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Transform.Descriptor instead.
func (Transform) EnumDescriptor() ([]byte, []int) {
	return file_streamline_v1_feature_registry_proto_rawDescGZIP(), []int{1}
}

// Aggregation collapses a numeric feature's running Redis state into one value at score time.
type Aggregation int32

const (
	Aggregation_AGGREGATION_UNSPECIFIED Aggregation = 0
	Aggregation_AGGREGATION_MEAN        Aggregation = 1 // running average
	Aggregation_AGGREGATION_CV          Aggregation = 2 // stddev / mean
	Aggregation_AGGREGATION_LAST        Aggregation = 3 // most recent value
	Aggregation_AGGREGATION_MAX         Aggregation = 4 // running maximum
)

// Enum value maps for Aggregation.
var (
	Aggregation_name = map[int32]string{
		0: "AGGREGATION_UNSPECIFIED",
		1: "AGGREGATION_MEAN",
		2: "AGGREGATION_CV",
		3: "AGGREGATION_LAST",
		4: "AGGREGATION_MAX",
	}
	Aggregation_value = map[string]int32{
		"AGGREGATION_UNSPECIFIED": 0,
		"AGGREGATION_MEAN":        1,
		"AGGREGATION_CV":          2,
		"AGGREGATION_LAST":        3,
		"AGGREGATION_MAX":         4,
	}
)

func (x Aggregation) Enum() *Aggregation {
	p := new(Aggregation)
	*p = x
	return p
}

func (x Aggregation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Aggregation) Descriptor() protoreflect.EnumDescriptor {
	return file_streamline_v1_feature_registry_proto_enumTypes[2].Descriptor()
}

func (Aggregation) Type() protoreflect.EnumType {
	return &file_streamline_v1_feature_registry_proto_enumTypes[2]
}

func (x Aggregation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Aggregation.Descriptor instead.
func (Aggregation) EnumDescriptor() ([]byte, []int) {
	return file_streamline_v1_feature_registry_proto_rawDescGZIP(), []int{2}
}

// Field names a property of the raw HTTP event.
// Used by HLL_DISTINCT (which value to dedupe) and ENTROPY (which value to track).
type Field int32

const (
	Field_FIELD_UNSPECIFIED Field = 0
	Field_FIELD_URI         Field = 1
	Field_FIELD_HTTP_METHOD Field = 2
)

// Enum value maps for Field.
var (
	Field_name = map[int32]string{
		0: "FIELD_UNSPECIFIED",
		1: "FIELD_URI",
		2: "FIELD_HTTP_METHOD",
	}
	Field_value = map[string]int32{
		"FIELD_UNSPECIFIED": 0,
		"FIELD_URI":         1,
		"FIELD_HTTP_METHOD": 2,
	}
)

func (x Field) Enum() *Field {
	p := new(Field)
	*p = x
	return p
}

func (x Field) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Field) Descriptor() protoreflect.EnumDescriptor {
	return file_streamline_v1_feature_registry_proto_enumTypes[3].Descriptor()
}

func (Field) Type() protoreflect.EnumType {
	return &file_streamline_v1_feature_registry_proto_enumTypes[3]
}

func (x Field) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Field.Descriptor instead.
func (Field) EnumDescriptor() ([]byte, []int) {
	return file_streamline_v1_feature_registry_proto_rawDescGZIP(), []int{3}
}

// FeatureDef declares one feature.
type FeatureDef struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type               FeatureType            `protobuf:"varint,2,opt,name=type,proto3,enum=streamline.v1.FeatureType" json:"type,omitempty"`
	Transform          Transform              `protobuf:"varint,3,opt,name=transform,proto3,enum=streamline.v1.Transform" json:"transform,omitempty"`
	Aggregation        Aggregation            `protobuf:"varint,4,opt,name=aggregation,proto3,enum=streamline.v1.Aggregation" json:"aggregation,omitempty"`
	Field              Field                  `protobuf:"varint,5,opt,name=field,proto3,enum=streamline.v1.Field" json:"field,omitempty"`
	NumeratorPredicate string                 `protobuf:"bytes,6,opt,name=numerator_predicate,json=numeratorPredicate,proto3" json:"numerator_predicate,omitempty"`
	Denominator        string                 `protobuf:"bytes,7,opt,name=denominator,proto3" json:"denominator,omitempty"`
	DenominatorOffset  int32                  `protobuf:"varint,8,opt,name=denominator_offset,json=denominatorOffset,proto3" json:"denominator_offset,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FeatureDef) Reset() {
	*x = FeatureDef{}
	mi := &file_streamline_v1_feature_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureDef) ProtoMessage() {}

func (x *FeatureDef) ProtoReflect() protoreflect.Message {
	mi := &file_streamline_v1_feature_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureDef.ProtoReflect.Descriptor instead.
func (*FeatureDef) Descriptor() ([]byte, []int) {
	return file_streamline_v1_feature_registry_proto_rawDescGZIP(), []int{0}
}

func (x *FeatureDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FeatureDef) GetType() FeatureType {
	if x != nil {
		return x.Type
	}
	return FeatureType_FEATURE_TYPE_UNSPECIFIED
}

func (x *FeatureDef) GetTransform() Transform {
	if x != nil {
		return x.Transform
	}
	return Transform_TRANSFORM_UNSPECIFIED
}

func (x *FeatureDef) GetAggregation() Aggregation {
	if x != nil {
		return x.Aggregation
	}
	return Aggregation_AGGREGATION_UNSPECIFIED
}

func (x *FeatureDef) GetField() Field {
	if x != nil {
		return x.Field
	}
	return Field_FIELD_UNSPECIFIED
}

func (x *FeatureDef) GetNumeratorPredicate() string {
	if x != nil {
		return x.NumeratorPredicate
	}
	return ""
}

func (x *FeatureDef) GetDenominator() string {
	if x != nil {
		return x.Denominator
	}
	return ""
}

func (x *FeatureDef) GetDenominatorOffset() int32 {
	if x != nil {
		return x.DenominatorOffset
	}
	return 0
}

type Registry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Features      []*FeatureDef          `protobuf:"bytes,1,rep,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registry) Reset() {
	*x = Registry{}
	mi := &file_streamline_v1_feature_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registry) ProtoMessage() {}

func (x *Registry) ProtoReflect() protoreflect.Message {
	mi := &file_streamline_v1_feature_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registry.ProtoReflect.Descriptor instead.
func (*Registry) Descriptor() ([]byte, []int) {
	return file_streamline_v1_feature_registry_proto_rawDescGZIP(), []int{1}
}

func (x *Registry) GetFeatures() []*FeatureDef {
	if x != nil {
		return x.Features
	}
	return nil
}

var File_streamline_v1_feature_registry_proto protoreflect.FileDescriptor

const file_streamline_v1_feature_registry_proto_rawDesc = "" +
	"\n" +
	"$streamline/v1/feature_registry.proto\x12\rstreamline.v1\"\xf4\x02\n" +
	"\n" +
	"FeatureDef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12.\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1a.streamline.v1.FeatureTypeR\x04type\x126\n" +
	"\ttransform\x18\x03 \x01(\x0e2\x18.streamline.v1.TransformR\ttransform\x12<\n" +
	"\vaggregation\x18\x04 \x01(\x0e2\x1a.streamline.v1.AggregationR\vaggregation\x12*\n" +
	"\x05field\x18\x05 \x01(\x0e2\x14.streamline.v1.FieldR\x05field\x12/\n" +
	"\x13numerator_predicate\x18\x06 \x01(\tR\x12numeratorPredicate\x12 \n" +
	"\vdenominator\x18\a \x01(\tR\vdenominator\x12-\n" +
	"\x12denominator_offset\x18\b \x01(\x05R\x11denominatorOffset\"A\n" +
	"\bRegistry\x125\n" +
	"\bfeatures\x18\x01 \x03(\v2\x19.streamline.v1.FeatureDefR\bfeatures*\xc9\x01\n" +
	"\vFeatureType\x12\x1c\n" +
	"\x18FEATURE_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12FEATURE_TYPE_COUNT\x10\x01\x12\x18\n" +
	"\x14FEATURE_TYPE_NUMERIC\x10\x02\x12\x16\n" +
	"\x12FEATURE_TYPE_RATIO\x10\x03\x12\x1d\n" +
	"\x19FEATURE_TYPE_HLL_DISTINCT\x10\x04\x12\x18\n" +
	"\x14FEATURE_TYPE_ENTROPY\x10\x05\x12\x19\n" +
	"\x15FEATURE_TYPE_TIME_GAP\x10\x06*S\n" +
	"\tTransform\x12\x19\n" +
	"\x15TRANSFORM_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TRANSFORM_IDENTITY\x10\x01\x12\x13\n" +
	"\x0fTRANSFORM_LOG1P\x10\x02*\x7f\n" +
	"\vAggregation\x12\x1b\n" +
	"\x17AGGREGATION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10AGGREGATION_MEAN\x10\x01\x12\x12\n" +
	"\x0eAGGREGATION_CV\x10\x02\x12\x14\n" +
	"\x10AGGREGATION_LAST\x10\x03\x12\x13\n" +
	"\x0fAGGREGATION_MAX\x10\x04*D\n" +
	"\x05Field\x12\x15\n" +
	"\x11FIELD_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tFIELD_URI\x10\x01\x12\x15\n" +
	"\x11FIELD_HTTP_METHOD\x10\x02BTZRgithub.com/JDucr17/streamline/services/pipeline/internal/extractor/proto;featurepbb\x06proto3"

var (
	file_streamline_v1_feature_registry_proto_rawDescOnce sync.Once
	file_streamline_v1_feature_registry_proto_rawDescData []byte
)

func file_streamline_v1_feature_registry_proto_rawDescGZIP() []byte {
	file_streamline_v1_feature_registry_proto_rawDescOnce.Do(func() {
		file_streamline_v1_feature_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamline_v1_feature_registry_proto_rawDesc), len(file_streamline_v1_feature_registry_proto_rawDesc)))
	})
	return file_streamline_v1_feature_registry_proto_rawDescData
}

var file_streamline_v1_feature_registry_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_streamline_v1_feature_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_streamline_v1_feature_registry_proto_goTypes = []any{
	(FeatureType)(0),   // 0: streamline.v1.FeatureType
	(Transform)(0),     // 1: streamline.v1.Transform
	(Aggregation)(0),   // 2: streamline.v1.Aggregation
	(Field)(0),         // 3: streamline.v1.Field
	(*FeatureDef)(nil), // 4: streamline.v1.FeatureDef
	(*Registry)(nil),   // 5: streamline.v1.Registry
}
var file_streamline_v1_feature_registry_proto_depIdxs = []int32{
	0, // 0: streamline.v1.FeatureDef.type:type_name -> streamline.v1.FeatureType
	1, // 1: streamline.v1.FeatureDef.transform:type_name -> streamline.v1.Transform
	2, // 2: streamline.v1.FeatureDef.aggregation:type_name -> streamline.v1.Aggregation
	3, // 3: streamline.v1.FeatureDef.field:type_name -> streamline.v1.Field
	4, // 4: streamline.v1.Registry.features:type_name -> streamline.v1.FeatureDef
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_streamline_v1_feature_registry_proto_init() }
func file_streamline_v1_feature_registry_proto_init() {
	if File_streamline_v1_feature_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamline_v1_feature_registry_proto_rawDesc), len(file_streamline_v1_feature_registry_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamline_v1_feature_registry_proto_goTypes,
		DependencyIndexes: file_streamline_v1_feature_registry_proto_depIdxs,
		EnumInfos:         file_streamline_v1_feature_registry_proto_enumTypes,
		MessageInfos:      file_streamline_v1_feature_registry_proto_msgTypes,
	}.Build()
	File_streamline_v1_feature_registry_proto = out.File
	file_streamline_v1_feature_registry_proto_goTypes = nil
	file_streamline_v1_feature_registry_proto_depIdxs = nil
}
